############# Basic Settings #############
# site title
title: Tangerine's Blog
# site description, used in meta tags
description: A blog using Tangerine theme, powered by Jekyll.
# site keywords, used in meta tags
keywords:
  - blog
  - jekyll
  - tangerine
  - theme
  - jekyll-theme
# author information
author:
  name: Tangerine
  link: https://github.com/WCY-dt/tangerine
  email: mail@ch3nyang.top
# site language
lang: zh-CN
# site timezone
timezone: Asia/Shanghai
# display powered by jekyll in footer
powered_by: false
# the subpath of your site
baseurl: /
# the base hostname & protocol for your site
url: https://tangerine.ch3nyang.top
# OPTIONAL settings: delete the following line if you don't need
# https://giscus.app/
giscus:
  data-repo: WCY-dt/tangerine
  data-repo-id: R_kgDOMcELBQ
  data-category-id: DIC_kwDOMcELBc4ChP42
# google_analytics: G-XXXXXXXXXX
# umami: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
# baidu_site_verification: codeva-xxxxxxxxxx

############# Theme Settings #############
# color theme: light or dark
color_theme: light

# icons are from https://fonts.google.com/icons
navy:
  - title: post
    url: /
    icon: collections_bookmark
  - title: demo
    url: https://blog.ch3nyang.top
    icon: note_stack
  - title: category
    url: /category/
    icon: category
  - title: tag
    url: /tag/
    icon: local_offer
  - title: rss
    url: feed.xml
    icon: rss_feed

share:
  - hackernews
  - twitter
  - facebook
  - reddit
  - telegram
# - weibo

############# Other Settings #############
# Please do not modify the following settings unless you know what you are doing.
permalink: /post/:title/
theme_config:
  date_format: "%Y-%m"
markdown: kramdown
highlighter: rouge # Supported language: https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers
kramdown:
  input: GFM
jekyll-archives:
  enabled: [categories, tags, year]
  layouts: archive
  permalinks:
    tag: /tag/:name/
    category: /category/:name/
    year: /year/:year/
plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-loading-lazy
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
exclude:
  - LICENSE.txt
  - README.md